basePath: /api/v1
info:
  contact:
    email: https://forklift-dev@konveyor.io
    name: Konveyor - Forklift development team
    url: https://forklift.konveyor.io
  description: This is the inventory componenat of the Forklift project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Forklift Inventory API
  version: "1.0"
paths: {}
swagger: "2.0"
